// DO NOT EDIT BY HAND
// Generated by `scripts/generate-explore.js` at 2022-11-07T16:31:03.482Z.
// You can adjust the examples in ui/explore, then run `node scripts/generate-explore.js`.

export const apiItems = [
  {
    label: "Reading Data",
    value: "1-reading-data",
    functions: [
      {
        name: "Find Records",
        jsCodeBlocks: [
          "// Find all posts\nconst allPosts = await prisma.post.findMany()",
          "// Find a user by ID\nconst userById = await prisma.user.findUnique({\n  where: {\n    id: 2\n  }\n})",
          "// Find a user by email\nconst userByEmail = await prisma.user.findUnique({\n  where: {\n    email: 'ada@prisma.io'\n  },\n})",
          "// Find the first user that starts with Ada\nconst userByName = await prisma.user.findFirst({\n  where: {\n    name: {\n      startsWith: 'Ada'\n    }\n  },\n})",
          "// Select specific fields\nconst userName = await prisma.user.findUnique({\n  where: {\n    email: 'ada@prisma.io',\n  },\n  select: {\n    name: true,\n    email: true,\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Find all posts\nconst allPosts: Post[] = await prisma.post.findMany()",
          "// Find a user by ID\nconst userById: User | null = await prisma.user.findUnique({\n  where: {\n    id: 2,\n  },\n})",
          "// Find a user by email\nconst userByEmail = await prisma.user.findUnique({\n  where: {\n    email: 'ada@prisma.io',\n  },\n})",
          "// Find the first user that contains Ada\nconst userByName = await prisma.user.findFirst({\n  where: {\n    name: {\n      contains: 'Ada',\n    },\n  },\n})",
          "// Select specific fields\nconst userName = await prisma.user.findUnique({\n  where: {\n    email: 'ada@prisma.io',\n  },\n  select: {\n    name: true,\n    email: true,\n  },\n})",
        ],
      },
      {
        name: "Traverse Relations",
        jsCodeBlocks: [
          "// Retrieve the posts of a user\nconst postsByUser = await prisma.user\n  .findUnique({ where: { email: 'ada@prisma.io' } })\n  .posts()",
          "// Retrieve the categories of a post\nconst categoriesOfPost = await prisma.post\n  .findUnique({ where: { id: 1 } })\n  .categories()",
          "// Retrieve the profile of a user via a specific post\nconst authorProfile = await prisma.post\n  .findUnique({ where: { id: 1 } })\n  .author()\n  .profile()",
          "// Return all users and include their posts and profile\nconst users = await prisma.user.findMany({\n  include: {\n    posts: true,\n    profile: true,\n  },\n})",
          "// Select all users and all their post titles\nconst userPosts = await prisma.user.findMany({\n  select: {\n    name: true,\n    posts: {\n      select: {\n        title: true,\n      },\n    },\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Retrieve the posts of a user\nconst postsByUser: Post[] = await prisma.user\n  .findUnique({ where: { email: 'ada@prisma.io' } })\n  .posts()",
          "// Retrieve the categories of a post\nconst categoriesOfPost: Category[] = await prisma.post\n  .findUnique({ where: { id: 1 } })\n  .categories()",
          "// Retrieve the profile of a user via a specific post\nconst authorProfile: Profile | null = await prisma.post\n  .findUnique({ where: { id: 1 } })\n  .author()\n  .profile()",
          "// Return all users and include their posts and profile\nconst users: User[] = await prisma.user.findMany({\n  include: {\n    posts: true,\n    profile: true,\n  },\n})",
          "// Select all users and all their post titles\nconst userPosts = await prisma.user.findMany({\n  select: {\n    name: true,\n    posts: {\n      select: {\n        title: true,\n      },\n    },\n  },\n})",
        ],
      },
      {
        name: "Order By, Limits & Cursors",
        jsCodeBlocks: [
          "// Sort posts alphabetically\nconst alphabeticPosts = await prisma.post.findMany({\n  orderBy: { title: 'asc' },\n})",
          "// Order by most prolific authors\nconst prolificAuthors = await prisma.user.findMany({\n  orderBy: {\n    posts: {\n      _count: 'asc',\n    },\n  },\n})",
          "// Find the second page of posts\nconst secondPagePosts = await prisma.post.findMany({\n  take: 5,\n  skip: 5,\n})",
          "// Find the last 5 posts\nconst lastPosts = await prisma.post.findMany({\n  take: -5,\n})",
          "// Find the next 5 posts after post id 2\nconst paginatedPosts3 = await prisma.post.findMany({\n  take: 5,\n  cursor: {\n    id: 2,\n  },\n})",
          "// Find the last 5 posts before post id 2\nconst paginatedPosts4 = await prisma.post.findMany({\n  take: -5,\n  cursor: {\n    id: 11,\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Sort posts alphabetically\nconst alphabeticPosts: Post[] = await prisma.post.findMany({\n  orderBy: { title: 'asc' },\n})",
          "// Order by most prolific authors\nconst prolificAuthors: Category[] = await prisma.user.findMany({\n  orderBy: {\n    posts: {\n      _count: 'asc',\n    },\n  },\n})",
          "// Find the second page of posts\nconst secondPagePosts: Post[] = await prisma.post.findMany({\n  take: 5,\n  skip: 5,\n})",
          "// Find the last 5 posts\nconst lastPosts: Post[] = await prisma.post.findMany({\n  take: -5,\n})",
          "// Find the next 5 posts after post id 2\nconst paginatedPosts3: Post[] = await prisma.post.findMany({\n  take: 5,\n  cursor: {\n    id: 2,\n  },\n})",
          "// Find the last 5 posts before post id 2\nconst paginatedPosts4: Post[] = await prisma.post.findMany({\n  take: -5,\n  cursor: {\n    id: 11,\n  },\n})",
        ],
      },
      {
        name: "Aggregates & Group By",
        jsCodeBlocks: [
          "// Count the number of users\nconst count = await prisma.user.count()",
          "// Average age of our users\nconst averageAge = await prisma.user.aggregate({\n  _avg: {\n    age: true,\n  },\n})",
          "// Group users by country\nconst groupUsers = await prisma.user.groupBy({\n  by: ['country'],\n  _count: {\n    id: true,\n  },\n})",
          "// Group users by country with more than 3 users.\nconst usersByCountry = await prisma.user.groupBy({\n  by: ['country'],\n  _count: {\n    country: true,\n  },\n  having: {\n    country: {\n      _count: {\n        gt: 3,\n      },\n    },\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Count the number of users\nconst count = await prisma.user.count()",
          "// Average age of our users\nconst averageAge = await prisma.user.aggregate({\n  _avg: {\n    age: true,\n  },\n})",
          "// Group users by country\nconst groupUsers = await prisma.user.groupBy({\n  by: ['country'],\n  _count: {\n    id: true,\n  },\n})",
          "// Group users by country with more than 3 users.\nconst usersByCountry = await prisma.user.groupBy({\n  by: ['country'],\n  _count: {\n    country: true,\n  },\n  having: {\n    country: {\n      _count: {\n        gt: 3,\n      },\n    },\n  },\n})",
        ],
      },
    ],
  },
  {
    label: "Writing Data",
    value: "2-writing-data",
    functions: [
      {
        name: "Create Records",
        jsCodeBlocks: [
          "// Create a user\nconst user = await prisma.user.create({\n  data: {\n    email: 'elsa@prisma.io',\n    name: 'Elsa Prisma',\n    country: 'Italy',\n    age: 30,\n  },\n})",
          "// Create a user and two posts\nconst userWithPosts = await prisma.user.create({\n  data: {\n    email: 'elsa@prisma.io',\n    name: 'Elsa Prisma',\n    country: 'Italy',\n    age: 30,\n    posts: {\n      create: [\n        {\n          title: 'Include this post!',\n        },\n        {\n          title: 'Include this post!',\n        },\n      ],\n    },\n  },\n})",
          "// Create a customer and connect to a user\nconst profile = await prisma.profile.create({\n  data: {\n    bio: 'Flying Trapeze Artist. Prisma developer.',\n    user: {\n      connect: {\n        id: 10,\n      },\n    },\n  },\n})",
          "// Create many users at once\nconst users = await prisma.user.createMany({\n  data: [\n    {\n      name: 'Bob',\n      email: 'bob@prisma.io',\n      country: 'USA',\n      age: 24,\n    },\n    {\n      name: 'Yewande',\n      email: 'yewande@prisma.io',\n      country: 'Zimbabwe',\n      age: 19,\n    },\n    {\n      name: 'Angelique',\n      email: 'angelique@prisma.io',\n      country: 'Greece',\n      age: 43,\n    },\n  ],\n})",
          "// Create many users at once while skipping duplicates\nconst moreUsers = await prisma.user.createMany({\n  data: [\n    {\n      name: 'Bob',\n      email: 'bob@prisma.io',\n      country: 'USA',\n      age: 24,\n    },\n    {\n      name: 'Bobby',\n      email: 'bob@prisma.io',\n      country: 'United States of America',\n      age: 24,\n    }, // Duplicate unique key is ignored!\n    {\n      name: 'Yewande',\n      email: 'yewande@prisma.io',\n      country: 'Zimbabwe',\n      age: 19,\n    },\n    {\n      name: 'Angelique',\n      email: 'angelique@prisma.io',\n      country: 'Greece',\n      age: 43,\n    },\n  ],\n  skipDuplicates: true, // Skip 'Bobby'\n})",
        ],
        tsCodeBlocks: [
          "// Create a user\nconst user: User = await prisma.user.create({\n  data: {\n    email: 'elsa@prisma.io',\n    name: 'Elsa Prisma',\n    country: 'Italy',\n    age: 30,\n  },\n})",
          "// Create a user and two posts\nconst userWithPosts: User = await prisma.user.create({\n  data: {\n    email: 'elsa@prisma.io',\n    name: 'Elsa Prisma',\n    country: 'Italy',\n    age: 30,\n    posts: {\n      create: [\n        {\n          title: 'Include this post!',\n        },\n        {\n          title: 'Include this post!',\n        },\n      ],\n    },\n  },\n})",
          "// Create a customer and connect to a user\nconst profile: Profile = await prisma.profile.create({\n  data: {\n    bio: 'Flying Trapeze Artist. Prisma developer.',\n    user: {\n      connect: {\n        id: 10,\n      },\n    },\n  },\n})",
          "// Create many users at once\nconst users: Prisma.BatchPayload = await prisma.user.createMany({\n  data: [\n    {\n      name: 'Bob',\n      email: 'bob@prisma.io',\n      country: 'USA',\n      age: 24,\n    },\n    {\n      name: 'Yewande',\n      email: 'yewande@prisma.io',\n      country: 'Zimbabwe',\n      age: 19,\n    },\n    {\n      name: 'Angelique',\n      email: 'angelique@prisma.io',\n      country: 'Greece',\n      age: 43,\n    },\n  ],\n})",
          "// Create many users at once while skipping duplicates\nconst moreUsers: Prisma.BatchPayload = await prisma.user.createMany({\n  data: [\n    {\n      name: 'Bob',\n      email: 'bob@prisma.io',\n      country: 'USA',\n      age: 24,\n    },\n    {\n      name: 'Bobby',\n      email: 'bob@prisma.io',\n      country: 'United States of America',\n      age: 24,\n    }, // Duplicate unique key is ignored!\n    {\n      name: 'Yewande',\n      email: 'yewande@prisma.io',\n      country: 'Zimbabwe',\n      age: 19,\n    },\n    {\n      name: 'Angelique',\n      email: 'angelique@prisma.io',\n      country: 'Greece',\n      age: 43,\n    },\n  ],\n  skipDuplicates: true, // Skip 'Bobby'\n})",
        ],
      },
      {
        name: "Update Records",
        jsCodeBlocks: [
          "// Update an existing user\nconst alice = await prisma.user.update({\n  data: {\n    role: 'ADMIN',\n  },\n  where: {\n    email: 'alice@prisma.io',\n  },\n})",
          "// Change the author of a post in a single transaction\nconst updatedPost = await prisma.post.update({\n  where: {\n    id: 2,\n  },\n  data: {\n    author: {\n      connect: {\n        email: 'alice@prisma.io',\n      },\n    },\n  },\n})",
          "// Connect a post to a user, creating the post if it isn't found\nconst updatedUser = await prisma.user.update({\n  where: {\n    id: 1,\n  },\n  data: {\n    posts: {\n      connectOrCreate: {\n        create: {\n          title: 'The Gray Gatsby',\n        },\n        where: {\n          id: 10,\n        },\n      },\n    },\n  },\n})",
          "// Update all users with the country Deutschland\nconst updatedUsers = await prisma.user.updateMany({\n  data: {\n    country: 'Germany',\n  },\n  where: {\n    country: 'Deutschland',\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Update an existing user\nconst alice: User = await prisma.user.update({\n  data: {\n    role: 'ADMIN',\n  },\n  where: {\n    email: 'alice@prisma.io',\n  },\n})",
          "// Change the author of a post in a single transaction\nconst updatedPost: Post = await prisma.post.update({\n  where: {\n    id: 2,\n  },\n  data: {\n    author: {\n      connect: {\n        email: 'alice@prisma.io',\n      },\n    },\n  },\n})",
          "// Connect a post to a user, creating the post if it isn't found\nconst updatedUser: User = await prisma.user.update({\n  where: {\n    id: 1,\n  },\n  data: {\n    posts: {\n      connectOrCreate: {\n        create: {\n          title: 'The Gray Gatsby',\n        },\n        where: {\n          id: 10,\n        },\n      },\n    },\n  },\n})",
          "// Update all users with the country Deutschland\nconst updatedUsers: Prisma.BatchPayload = await prisma.user.updateMany({\n  data: {\n    country: 'Germany',\n  },\n  where: {\n    country: 'Deutschland',\n  },\n})",
        ],
      },
      {
        name: "Delete Records",
        jsCodeBlocks: [
          "// Delete an existing user\nconst deletedUser = await prisma.user.delete({\n  where: {\n    email: 'alice@prisma.io',\n  },\n})",
          "// Delete all the admins at once\nconst deletedAdmins = await prisma.user.deleteMany({\n  where: {\n    role: 'ADMIN',\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Delete an existing user\nconst deletedUser: User = await prisma.user.delete({\n  where: {\n    email: 'alice@prisma.io',\n  },\n})",
          "// Delete all the admins at once\nconst deletedAdmins: Prisma.BatchPayload = await prisma.user.deleteMany({\n  where: {\n    role: 'ADMIN',\n  },\n})",
        ],
      },
      {
        name: "Upsert Records",
        jsCodeBlocks: [
          "// Create Alice or update her role to admin.\nconst alice = await prisma.user.upsert({\n  update: {\n    role: 'ADMIN',\n  },\n  where: {\n    email: 'alice@prisma.io',\n  },\n  create: {\n    name: 'Alice',\n    email: 'alice@prisma.io',\n    country: 'England',\n    role: 'ADMIN',\n    age: 43,\n  },\n})",
        ],
        tsCodeBlocks: [
          "// Create Alice or update her role to admin.\nconst alice: User = await prisma.user.upsert({\n  update: {\n    role: 'ADMIN',\n  },\n  where: {\n    email: 'alice@prisma.io',\n  },\n  create: {\n    name: 'Alice',\n    email: 'alice@prisma.io',\n    country: 'England',\n    role: 'ADMIN',\n    age: 43,\n  },\n})",
        ],
      },
    ],
  },
  {
    label: "Advanced Patterns",
    value: "3-advanced-patterns",
    functions: [
      {
        name: "Transactions",
        jsCodeBlocks: [
          '// Create Bob and update Carol as a batch within a transaction\nawait prisma.$transaction([\n  prisma.user.create({\n    data: {\n      name: "Bob",\n      email: "bob@prisma.io",\n      age: 49,\n      country: "USA",\n    },\n  }),\n  prisma.user.update({\n    where: {\n      email: "carol@prisma.io"\n    },\n    data: {\n      country: "Germany",\n    },\n  }),\n])',
          "  // Example function turning an email into a country\n  const locate = async (email) => ({ country: 'Germany' })\n  const geo = await locate(bob.email)\n  return await tx.user.update({\n    where: {\n      id: bob.id,\n    },\n    data: {\n      country: geo.country,\n    },\n  })\n})",
        ],
        tsCodeBlocks: [
          "// Create Bob and update Carol as a batch within a transaction\nawait prisma.$transaction([\n  prisma.user.create({\n    data: {\n      name: 'Bob',\n      email: 'bob@prisma.io',\n      age: 49,\n      country: 'USA',\n    },\n  }),\n  prisma.user.update({\n    where: {\n      email: 'carol@prisma.io',\n    },\n    data: {\n      country: 'Germany',\n    },\n  }),\n])",
          "  // Example function turning an email into a country\n  const locate = async (email: string) => ({ country: 'Germany' })\n  const geo = await locate(bob.email)\n  return await tx.user.update({\n    where: {\n      id: bob.id,\n    },\n    data: {\n      country: geo.country,\n    },\n  })\n})",
        ],
      },
      {
        name: "Middleware",
        jsCodeBlocks: [
          "// Timing middleware\nprisma.$use(async (params, next) => {\n  const before = Date.now()\n  const result = await next(params)\n  const after = Date.now()\n  console.log(\n    `Query ${params.model}.${params.action} took ${after - before}ms`,\n  )\n  return result\n})",
          "// Hash a User password automatically\nprisma.$use(async (params, next) => {\n  if (params.model === 'User') {\n    if (params.action === 'create' || params.action === 'update') {\n      if (params.args.data.password) {\n        const hashPass = hash(params.args.data.password)\n        params.args.data.password = hashPass\n      }\n    }\n  }\n  return next(params)\n})",
        ],
        tsCodeBlocks: [
          "// Timing middleware\nprisma.$use(async (params, next) => {\n  const before = Date.now()\n  const result = await next(params)\n  const after = Date.now()\n  console.log(\n    `Query ${params.model}.${params.action} took ${after - before}ms`,\n  )\n  return result\n})",
          "// Hash a User password automatically\nprisma.$use(async (params, next) => {\n  if (params.model === 'User') {\n    if (params.action === 'create' || params.action === 'update') {\n      if (params.args.data.password) {\n        const hashPass = hash(params.args.data.password)\n        params.args.data.password = hashPass\n      }\n    }\n  }\n  return next(params)\n})",
        ],
      },
      {
        name: "Raw Queries with TypedSQL",
        tsCodeBlocks: [
          '-- in selectUserByEmail.sql\nSELECT * FROM "User" WHERE email = ${email};\n\n // in app.ts\nconst users: User[] = await prisma.$queryRawTyped(selectUserByEmail(email))',
          '-- in select5PostsRandomly.sql\nSELECT * FROM "Post" order by random() limit 5\n\n // in app.ts\nconst posts: Post[] = await prisma.$queryRawTyped(select5PostsRandomly())',
          '-- in clearUsersTable.sql\nDELETE from "User"\n\n // in app.ts\nconst clearUsersTable = await prisma.$executeRawTyped(clearUsersTable())',
          '-- in dropUsersTable.sql\nTRUNCATE TABLE "User" CASCADE\n\n // in app.ts\nconst dropUsersTable = await prisma.$executeRawTyped(dropUsersTable())',
        ],
      },
      {
        name: "Logging",
        tsCodeBlocks: [
          "// Enable query logging\nconst prisma = new PrismaClient({\n  log: [\n    {\n      emit: 'event',\n      level: 'query',\n    },\n  ],\n})\nprisma.$on('query', (e) => {\n  console.log('Query: ' + e.query)\n  console.log('Params: ' + e.params)\n  console.log('Duration: ' + e.duration + 'ms')\n})",
        ],
      },
    ],
  },
  {
    label: "Prisma Schema",
    value: "4-prisma-schema",
    functions: [
      {
        name: "Data Model",
        prismaCodeBlock:
          '// This is your Prisma schema file. Learn more in the\n// documentation: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = "postgres"\n  url      = env("DATABASE_URL")\n}\n\ngenerator client {\n  provider        = "prisma-client-js"\n  previewFeatures = ["interactiveTransactions"]\n}\n\nmodel User {\n  id        Int      @id @default(autoincrement())\n  createdAt DateTime @default(now())\n  email     String   @unique\n  name      String\n  age       Int\n  role      Role     @default(USER)\n  country   String\n  posts     Post[]\n  profile   Profile?\n}\n\nmodel Profile {\n  id     Int    @id @default(autoincrement())\n  bio    String\n  user   User   @relation(fields: [userId], references: [id])\n  userId Int    @unique\n}\n\nmodel Post {\n  id         Int        @id @default(autoincrement())\n  createdAt  DateTime   @default(now())\n  title      String\n  published  Boolean    @default(false)\n  categories Category[] @relation(references: [id])\n  author     User       @relation(fields: [authorId], references: [id])\n  authorId   Int\n}\n\nmodel Category {\n  id    Int    @id @default(autoincrement())\n  name  String\n  posts Post[] @relation(references: [id])\n}\n\nenum Role {\n  USER\n  ADMIN\n}\n',
        jsCodeBlocks: [""],
        tsCodeBlocks: [""],
      },
    ],
  },
];
